"""
engine/architect.py
Phase 2 - 架构师: 脚手架生成与环境隔离.

根据 spec.json 创建子项目隔离目录, 初始化 venv,
生成 requirements.txt / 基础文件结构.
满足 [ENV_ISOLATION] [FRESH_DATA].
"""

from __future__ import annotations

import json
import logging
import subprocess
import sys
from pathlib import Path
from typing import Any

from engine.llm_client import LLMClient, Message

logger = logging.getLogger("autoforge.architect")


class Architect:
    """子项目脚手架生成器."""

    def __init__(self, llm: LLMClient, output_root: Path) -> None:
        self.llm = llm
        self.output_root = output_root

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------
    def scaffold(self, spec: dict[str, Any]) -> Path:
        """创建完整的子项目骨架, 返回项目根目录."""
        name = spec["name"]
        logger.info("=== Phase 2: Architect - 脚手架生成 [%s] ===", name)

        project_dir = self.output_root / name
        project_dir.mkdir(parents=True, exist_ok=True)

        # 1. 目录结构
        (project_dir / "src").mkdir(exist_ok=True)
        (project_dir / "tests").mkdir(exist_ok=True)

        # 2. 写入 spec.json
        spec_path = project_dir / "spec.json"
        spec_path.write_text(
            json.dumps(spec, indent=2, ensure_ascii=False), encoding="utf-8"
        )

        # 3. 生成 requirements.txt (锁定最新版本)
        self._generate_requirements(project_dir, spec.get("dependencies", []))

        # 4. 创建 venv [ENV_ISOLATION]
        self._create_venv(project_dir)

        # 5. 安装依赖
        self._install_deps(project_dir)

        # 6. 占位文件
        self._write_placeholder_files(project_dir, spec)

        logger.info("Scaffold 完成: %s", project_dir)
        return project_dir

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------
    def _generate_requirements(self, project_dir: Path, deps: list[str]) -> None:
        """生成 requirements.txt, 锁定依赖版本."""
        lines = ["# Auto-generated by AutoForge Architect", "pytest>=8.0,<9.0"]
        for dep in deps:
            lines.append(dep)
        req_path = project_dir / "requirements.txt"
        req_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        logger.info("requirements.txt generated (%d deps)", len(deps) + 1)

    @staticmethod
    def _create_venv(project_dir: Path) -> None:
        """创建 venv."""
        venv_dir = project_dir / ".venv"
        if venv_dir.exists():
            logger.info("venv already exists, skipping")
            return
        logger.info("Creating venv ...")
        subprocess.run(
            [sys.executable, "-m", "venv", str(venv_dir)],
            check=True,
            capture_output=True,
        )
        logger.info("venv created at %s", venv_dir)

    @staticmethod
    def _install_deps(project_dir: Path) -> None:
        """在 venv 中安装依赖."""
        venv_dir = project_dir / ".venv"
        if sys.platform == "win32":
            pip_exe = venv_dir / "Scripts" / "pip.exe"
        else:
            pip_exe = venv_dir / "bin" / "pip"

        req_file = project_dir / "requirements.txt"
        logger.info("Installing dependencies via pip ...")
        result = subprocess.run(
            [str(pip_exe), "install", "-r", str(req_file), "-q"],
            capture_output=True,
            text=True,
            timeout=300,
        )
        if result.returncode != 0:
            logger.error("pip install failed:\n%s", result.stderr)
            raise RuntimeError(f"pip install failed: {result.stderr[:500]}")
        logger.info("Dependencies installed successfully")

    @staticmethod
    def _write_placeholder_files(project_dir: Path, spec: dict[str, Any]) -> None:
        """生成占位源文件."""
        # src/__init__.py
        (project_dir / "src" / "__init__.py").write_text(
            f'"""Module: {spec["name"]}."""\n', encoding="utf-8"
        )
        # src/core.py placeholder
        (project_dir / "src" / "core.py").write_text(
            f'"""{spec["name"]} - 核心功能 (待 Coder 填充)."""\n', encoding="utf-8"
        )
        # tests/__init__.py
        (project_dir / "tests" / "__init__.py").write_text("", encoding="utf-8")
        # tests/test_core.py placeholder
        (project_dir / "tests" / "test_core.py").write_text(
            '"""Tests (待 Coder 填充)."""\n', encoding="utf-8"
        )
        # mcp_server.py placeholder
        (project_dir / "mcp_server.py").write_text(
            '"""MCP Server (待 MCPWrapper 填充)."""\n', encoding="utf-8"
        )
        # README.md
        readme = (
            f"# {spec['name']}\n\n"
            f"{spec.get('description', '')}\n\n"
            "## Features\n\n"
            + "\n".join(f"- {f}" for f in spec.get("features", []))
            + "\n\n*Auto-generated by AutoForge*\n"
        )
        (project_dir / "README.md").write_text(readme, encoding="utf-8")
        logger.info("Placeholder files written")
