"""
engine/architect.py
Phase 2 - 架构师: 脚手架生成与环境隔离.

根据 spec.json 创建子项目隔离目录, 初始化 venv,
生成 requirements.txt / 基础文件结构 / MCP 配置模板 / 环境自愈脚本.
满足 [ENV_ISOLATION] [FRESH_DATA] [MCP_NATIVE].
"""

from __future__ import annotations

import json
import logging
import subprocess
import sys
from pathlib import Path
from typing import Any

from engine.llm_client import LLMClient

logger = logging.getLogger("autoforge.architect")


class Architect:
    """子项目脚手架生成器."""

    def __init__(self, llm: LLMClient, output_root: Path) -> None:
        self.llm = llm
        self.output_root = output_root

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------
    def scaffold(self, spec: dict[str, Any]) -> Path:
        """创建完整的子项目骨架, 返回项目根目录."""
        name = spec["name"]
        logger.info("=== Phase 2: Architect - 脚手架生成 [%s] ===", name)

        project_dir = self.output_root / name
        project_dir.mkdir(parents=True, exist_ok=True)

        # 1. 目录结构
        (project_dir / "src").mkdir(exist_ok=True)
        (project_dir / "tests").mkdir(exist_ok=True)

        # 2. 写入 spec.json
        spec_path = project_dir / "spec.json"
        spec_path.write_text(
            json.dumps(spec, indent=2, ensure_ascii=False), encoding="utf-8"
        )

        # 3. 生成 requirements.txt (锁定最新版本)
        self._generate_requirements(project_dir, spec.get("dependencies", []))

        # 4. 创建 venv [ENV_ISOLATION]
        self._create_venv(project_dir)

        # 5. 安装依赖
        self._install_deps(project_dir)

        # 6. 占位文件
        self._write_placeholder_files(project_dir, spec)

        # 7. MCP 配置模板 [MCP_NATIVE]
        self._write_mcp_config(project_dir, spec)

        # 8. 环境自愈脚本 [FRESH_DATA]
        self._write_setup_scripts(project_dir, spec)

        logger.info("Scaffold 完成: %s", project_dir)
        return project_dir

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------
    def _generate_requirements(self, project_dir: Path, deps: list[str]) -> None:
        """生成 requirements.txt, 锁定依赖版本."""
        lines = ["# Auto-generated by AutoForge Architect", "pytest>=8.0,<9.0"]
        for dep in deps:
            lines.append(dep)
        req_path = project_dir / "requirements.txt"
        req_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        logger.info("requirements.txt generated (%d deps)", len(deps) + 1)

    @staticmethod
    def _create_venv(project_dir: Path) -> None:
        """创建 venv."""
        venv_dir = project_dir / ".venv"
        if venv_dir.exists():
            logger.info("venv already exists, skipping")
            return
        logger.info("Creating venv ...")
        subprocess.run(
            [sys.executable, "-m", "venv", str(venv_dir)],
            check=True,
            capture_output=True,
        )
        logger.info("venv created at %s", venv_dir)

    @staticmethod
    def _install_deps(project_dir: Path) -> None:
        """在 venv 中安装依赖."""
        venv_dir = project_dir / ".venv"
        if sys.platform == "win32":
            pip_exe = venv_dir / "Scripts" / "pip.exe"
        else:
            pip_exe = venv_dir / "bin" / "pip"

        req_file = project_dir / "requirements.txt"
        logger.info("Installing dependencies via pip ...")
        result = subprocess.run(
            [str(pip_exe), "install", "-r", str(req_file), "-q"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=300,
        )
        if result.returncode != 0:
            logger.error("pip install failed:\n%s", result.stderr)
            raise RuntimeError(f"pip install failed: {result.stderr[:500]}")
        logger.info("Dependencies installed successfully")

    @staticmethod
    def _write_placeholder_files(project_dir: Path, spec: dict[str, Any]) -> None:
        """生成占位源文件."""
        # src/__init__.py
        (project_dir / "src" / "__init__.py").write_text(
            f'"""Module: {spec["name"]}."""\n', encoding="utf-8"
        )
        # src/core.py placeholder
        (project_dir / "src" / "core.py").write_text(
            f'"""{spec["name"]} - 核心功能 (待 Coder 填充)."""\n', encoding="utf-8"
        )
        # tests/__init__.py
        (project_dir / "tests" / "__init__.py").write_text("", encoding="utf-8")
        # tests/test_core.py placeholder
        (project_dir / "tests" / "test_core.py").write_text(
            '"""Tests (待 Coder 填充)."""\n', encoding="utf-8"
        )
        # mcp_server.py placeholder
        (project_dir / "mcp_server.py").write_text(
            '"""MCP Server (待 MCPWrapper 填充)."""\n', encoding="utf-8"
        )
        # README.md
        readme = (
            f"# {spec['name']}\n\n"
            f"{spec.get('description', '')}\n\n"
            "## Features\n\n"
            + "\n".join(f"- {f}" for f in spec.get("features", []))
            + "\n\n"
            "## Quick Start\n\n"
            "```bash\n"
            "# Linux/Mac\n"
            "chmod +x setup_env.sh && ./setup_env.sh\n\n"
            "# Windows\n"
            "setup_env.bat\n"
            "```\n\n"
            "## MCP Integration\n\n"
            "Copy the content of `mcp_config.json` into your Claude Desktop "
            "configuration file to register this tool.\n\n"
            "*Auto-generated by AutoForge*\n"
        )
        (project_dir / "README.md").write_text(readme, encoding="utf-8")
        logger.info("Placeholder files written")

    @staticmethod
    def _write_mcp_config(project_dir: Path, spec: dict[str, Any]) -> None:
        """生成 mcp_config.json 模板, 可直接粘贴到 Claude Desktop 配置.

        [MCP_NATIVE] 增强: 开箱即用的 MCP 服务器注册配置.
        """
        name = spec["name"]
        # 生成可直接粘贴到 Claude Desktop 的配置
        mcp_config = {
            "mcpServers": {
                name: {
                    "command": "python",
                    "args": ["mcp_server.py"],
                    "cwd": str(project_dir.resolve()),
                    "env": {},
                }
            }
        }
        config_path = project_dir / "mcp_config.json"
        config_path.write_text(
            json.dumps(mcp_config, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        logger.info("mcp_config.json generated (Claude Desktop compatible)")

    @staticmethod
    def _write_setup_scripts(project_dir: Path, spec: dict[str, Any]) -> None:
        """生成环境自愈脚本: setup_env.sh (Linux/Mac) + setup_env.bat (Windows).

        [FRESH_DATA] 一键创建 venv 并安装所有锁定依赖.
        """
        name = spec["name"]

        # --- setup_env.sh (Linux/Mac) ---
        sh_content = f"""#!/usr/bin/env bash
# ============================================================
# {name} - Environment Setup Script (Auto-generated by AutoForge)
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=== Setting up {name} environment ==="

# 1. Create virtual environment
if [ ! -d ".venv" ]; then
    echo "[1/3] Creating virtual environment ..."
    python3 -m venv .venv
else
    echo "[1/3] Virtual environment already exists, skipping ..."
fi

# 2. Activate venv
echo "[2/3] Activating virtual environment ..."
source .venv/bin/activate

# 3. Install dependencies
echo "[3/3] Installing dependencies ..."
pip install -r requirements.txt -q

echo ""
echo "=== Setup complete! ==="
echo "To activate:  source .venv/bin/activate"
echo "To run MCP:   python mcp_server.py"
echo "To test:      pytest tests/ -v"
"""
        sh_path = project_dir / "setup_env.sh"
        sh_path.write_text(sh_content, encoding="utf-8", newline="\n")
        logger.info("setup_env.sh generated")

        # --- setup_env.bat (Windows) ---
        bat_content = f"""@echo off
REM ============================================================
REM {name} - Environment Setup Script (Auto-generated by AutoForge)
REM ============================================================

cd /d "%~dp0"

echo === Setting up {name} environment ===

REM 1. Create virtual environment
if not exist ".venv" (
    echo [1/3] Creating virtual environment ...
    python -m venv .venv
) else (
    echo [1/3] Virtual environment already exists, skipping ...
)

REM 2. Activate venv
echo [2/3] Activating virtual environment ...
call .venv\\Scripts\\activate.bat

REM 3. Install dependencies
echo [3/3] Installing dependencies ...
pip install -r requirements.txt -q

echo.
echo === Setup complete! ===
echo To activate:  .venv\\Scripts\\activate.bat
echo To run MCP:   python mcp_server.py
echo To test:      pytest tests/ -v
"""
        bat_path = project_dir / "setup_env.bat"
        bat_path.write_text(bat_content, encoding="utf-8", newline="\r\n")
        logger.info("setup_env.bat generated")
